### ISSUE TITLE
Create a roadmap

### ISSUE THREAD

**Issue by dguo** [dguo/make-a-readme#13]
This site has gotten good traction. According to Google Search Console, it now has an average search results position of 8 for queries like "readme", "create readme.md", and "readme template". It is also trending towards 3,600 hits a month, according to Google Analytics.

Now's a good time to come up with some ideas for making the site better. Some that I can think of off the top of my head:

* Translate the website. [Crowdin](https://crowdin.com/) might be a good solution. They have a free plan for open source projects, and [Docusaurus uses them](https://docusaurus.io/docs/en/translation). [LingoHub](https://lingohub.com/pricing/) and [PhraseApp](https://phraseapp.com/pricing) also have free options for open source.
* Do a check for accessibility. I don't have any experience with this, so it'll be a good learning opportunity.
* Create an interactive README generator.
* Show examples for individual sections or maybe even entire READMEs.

**Comment by theIsaacLim** [comment]
can i take on building some examples?

**Comment by davidak** [comment]
>Show examples for individual sections or maybe even entire READMEs.

I think we should just explain the sections and link to real projects as examples.

@theIsaacLim thanks for opening https://github.com/dguo/make-a-readme/issues/14

**Comment by dguo** [comment]
@theIsaacLim, thanks for taking the initiative. Definitely.
