### ISSUE TITLE
Support for emojis in preview

### ISSUE THREAD

**Issue by fredrikj31** [dguo/make-a-readme#27]
I was wondering if support for emojis in the preview would be a thing?

I saw many developers have in their repositories with emojis. It would be awesome if we could get a preview of the GitHub emoji.

What's your opinion on this?

**Comment by CityIsBetter** [comment]
![Screenshot 2023-06-19 095850](https://github.com/dguo/make-a-readme/assets/88649624/e44d959a-31fc-494e-af9d-536cdbdfc797)
emojis do work in preview

**Comment by fredrikj31** [comment]
I was thinking more of the way that Github markdown adds their emojis like this: `:smiley:` etc. It doesn't seem like there is support for that,

**Comment by CityIsBetter** [comment]
oh ok and btw i didnt copy paste, you could open up emoji panel in windows using windows key + .(period) and in mac i think it is 
ctrl+cmd+space
