### ISSUE TITLE
Overlaying Text in the Landing page

### ISSUE THREAD

**Issue by souravseal99** [dguo/make-a-readme#48]
## The " Try ReadMe.com " text in red, is overlaying with the description, when viewed on a smaller screen.

![Screenshot_20210629-145954_Chrome.jpg](https://user-images.githubusercontent.com/69809086/123774442-0784f400-d8eb-11eb-856a-e65b5edc0b92.jpg)

**Comment by dguo** [comment]
Hi @souravseal99, thanks for the report! I believe the issue is fixed now.
