### ISSUE TITLE
Suggestion: Where the s/w in question is library/framework like show a few code examples

### ISSUE THREAD

**Issue by paul-hammant** [dguo/make-a-readme#5]
Show a few stackoverflow style code examples if applicable.

* 1/3 of programmers prefer reference docs
* 1/3 of programmers prefer tutorials
* 1/3 of programmers prefer cohesive code examples

Why? stops 1/3 of people instantly hitting the back button.

**Comment by dguo** [comment]
There is a basic section for examples: https://www.makeareadme.com/#usage

But yeah, that could use some more details.

**Comment by paul-hammant** [comment]
I think versus what you said, some entry level examples need to be inline in the README. At a second level links off to other (VCS backed) examples would be good.  

There's a super-skilled class of example where the author has made a **whole repo** which is a self-contained example of the tech that is buildable and contains as little else as possible.  @jknack is accomplished with this for things like https://github.com/jooby-project/greeting which starts as a quickly buildable deployable thing and then smoothly folds into a tutorial.

^ Those should be linked into the README too :)

**Comment by dguo** [comment]
Those are some good points. I'll add them the next time I update the site.

Thanks!

**Comment by dguo** [comment]
Resolved by #9.
