### ISSUE TITLE
Suggestion: if s/w has a UI show a pertinent screenshot of the UI

### ISSUE THREAD

**Issue by paul-hammant** [dguo/make-a-readme#6]
Aids adoption; stops ppl hitting the back button so quickly.

**Comment by dguo** [comment]
Yep, there is a visuals section already: https://www.makeareadme.com/#visuals

Do you think it should be expanded somehow?

**Comment by paul-hammant** [comment]
My bad - I searched for UI in page. 

I'd blogged before on readme's and was going to circle back to it - https://paulhammant.com/2017/04/01/often-forgotten-must-haves-for-continuous-delivery-teams/

No need now as yours is great :)
